In [ ]:
#write down 20 in built method on pandas and 20 on numpy with examples each.

In [1]:
#write down 20 in built method on pandas with examples each.

In [ ]:
import pandas as pd
df = pd.DataFrame{"Name": ["Alo", "Roh", "Bim", "Rah", "Cha", "Viv"], "Age": [29, 23, 35, 25, 32, 38], 
                  "State": ["Lisbon", "Algav", "Vila-Rel", "Liera", "Manderia", "Lagos", "porto"], 
                  "Gender": ["Female", "male", "Female", "Male", "Male", "Female"], "Salary": [2000,1500,1700,1300,1900,2500]}
df

In [2]:
# 1. read_csv() function helps read a comma-separated values (csv) file into a Pandas DataFrame. 

In [ ]:
# 2. head(n) is used to return the first n rows of a dataset. By default, df.head() will return the first 5 rows of the DataFrame. 
#If you want more/less number of rows, you can specify n as an integer. e.g
data_1.head(6)

In [ ]:
# 3. describe() is used to generate descriptive statistics of the data in a Pandas DataFrame or Series.
# It summarizes central tendency and dispersion of the dataset. describe() helps in getting a quick overview of the dataset.e.g:
data_1.describe()

In [ ]:
# 4. memory_usage() returns a Pandas Series having the memory usage of each column (in bytes) in a Pandas DataFrame. 
# By specifying the deep attribute as True, we can get to know the actual space being taken by each column e.g:
data_1.memory_usage(deep=True)

In [ ]:
# 5. astype() is used to cast a Python object to a particular data type. 
# It can be a very helpful function in case your data is not stored in the correct format (data type). e.g:
data_1['Gender'] = data_1.Gender.astype('category')

In [ ]:
# 6. loc[:] helps to access a group of rows and columns in a dataset, a slice of the dataset, as per our requirement. 
#For instance, if we only want the last 2 rows and the first 3 columns of a dataset, we can access them with the help of loc[:].
data_1.loc[0:4, ['Name', 'Age', 'State']]

In [ ]:
# 7. to_datetime() converts a Python object to datetime format. It can take an integer, floating point number, list, Pandas Series, or Pandas DataFrame as argument. 
# to_datetime() is very powerful when the dataset has time series values or dates.
data_1['DOB'] = pd.to_datetime(data_1['DOB'])

In [ ]:
# 8. value_counts() returns a Pandas Series containing the counts of unique values.
#value_counts() will help us in identifying the number of occurrences of each unique value in a Series.
data_1['State'].value_counts()

In [ ]:
# 9. drop_duplicates() returns a Pandas DataFrame with duplicate rows removed. 
# Even among duplicates, there is an option to keep the first occurrence (record) of the duplicate or the last.
data_1.drop_duplicates(inplace=True)

In [ ]:
# 10. merge() is used to merge 2 Pandas DataFrame objects or a DataFrame and a Series object on a common column (field) e.g:
data_1.merge(data_2, on='Name', how='left')

In [ ]:
# 11. groupby() is used to group a Pandas DataFrame by 1 or more columns, and perform some mathematical operation on it. 
# groupby() can be used to summarize data in a simple manner.e.g:

data_1.groupby(by='State').Salary.mean()

In [ ]:
# 12. sort_values() is used to sort column in a Pandas DataFrame (or a Pandas Series) by values in ascending or descending order. 
# By specifying the inplace attribute as True, you can make a change directly in the original DataFrame. e.g:

data_1.sort_values(by='Name', inplace=True)

In [ ]:
# 13. fillna() helps to replace all NaN values in a DataFrame or Series by imputing these missing values with more appropriate values.
#NaN stands for “not a number”, and represents entries that were not populated in the original data source. 
#While populating the values in the DataFrame, Pandas makes sure that these entries can be identified separately by the user

data_1['City temp'].fillna(38.5, inplace=True)

In [ ]:
# 14. To create a DataFrame
import pandas as pd

df = pd.DataFrame({"col1": ["A0", "A1", "A0", "A2", "A0", "A1"], "col2": [1,2,3,4,5,6]})
df= column
column

In [37]:
df

col1  col2
0   A0     1
1   A1     2
2   A0     3
3   A2     4
4   A0     5
5   A1     6

In [17]:

df = pd.DataFrame
data_2=({"names": ["Ren", "Ayo", "Aki", "Zet", "Kin", "Box"], "age": [32, 36, 14, 25, 48, 29], "height": [5, 6, 5.2, 6.4, 5.7, 6]})
df=pd.DataFrame (data_2)


In [43]:
df

col1  col2
0   A0     1
1   A1     2
2   A0     3
3   A2     4
4   A0     5
5   A1     6

In [ ]:
# 15. iloc to retieve a column value from a DataFrame

# To retrieve the first column value
df.iloc[0].names
# To retrieve the last column value
df.iloc[-1].names

In [44]:
# 16. To create a DataFrame from a Panda series
df = pd.DataFrame(
    {
        "names": ["Ren", "Ayo", "Aki", "Zet", "Kin", "Box"], 
        "age": [30, 36, 14, 25, 48, 29], 
        "height": [9, 6, 5.2, 6.4, 5.7, 6],
        "Entry": [1, 2, 3, 4, 5, 6],
    }
)
df_group = df.groupby("names").age.sum()
df_group


names
Aki    14
Ayo    36
Box    29
Kin    48
Ren    30
Zet    25
Name: age, dtype: int64

In [45]:
df

names  age  height  Entry
0   Ren   30     9.0      1
1   Ayo   36     6.0      2
2   Aki   14     5.2      3
3   Zet   25     6.4      4
4   Kin   48     5.7      5
5   Box   29     6.0      6

In [46]:
df_group.to_frame()


age
names     
Aki     14
Ayo     36
Box     29
Kin     48
Ren     30
Zet     25

In [53]:
# 17. Dtypes shows the data type of each column
df.dtypes

names      object
age         int64
height    float64
Entry       int64
dtype: object

In [55]:
# 18. Shape and Size Since dataframes are two-dimensional, what shape returns is the number of rows and columns. It is a measure of how much data we have and a key input to the data analysis process.
df.shape

(6, 2)

In [56]:
#Size, as the name suggests, returns the size of a dataframe which is the number of rows multiplied by the number of columns.


df.size

12

In [57]:
# 19. Isna function returns a dataframe filled with boolean values with true indicating missing values.
df.isna().any()

col1    False
col2    False
dtype: bool

In [58]:
# 20. Identifying Missing Values Sum
df.isnull().sum()

col1    0
col2    0
dtype: int64

In [59]:
# 21. index() is an inbuilt function in Python, which searches for a given element from the start of the list and returns the lowest index where the element appears.
df.index

RangeIndex(start=0, stop=6, step=1)

In [67]:
# 1. Array: It is used to create an array from scratch or convert a list or pandas series object to an array.
import numpy as np
import pandas as pd
print(np.array ( [ 1, 2, 3, 4, 5, 6 ] ))
print(np.array(pd.Series([ 1, 2, 3, 4])))


[1 2 3 4 5 6]
[1 2 3 4]


In [ ]:
# 2. Arange creates an array in a range with a specified increment.eg
np.arange(2, 10, 2)
array([2, 4, 6, 8])

np.arrange(0, 20, 5)
array([0, 5, 10, 15])

In [ ]:
# 3. Linspace creates an array in a specified range with equidistant elements.

np.linspace(0, 20, 10)


In [80]:
#4. Unique returns the number of unique elements in an array. eg.
a=np.array([1,1,1,2,2,3])
np.unique(a)
np.unique(a, return_counts=True)


(array([1, 2, 3]), array([3, 2, 1], dtype=int64))

In [73]:
#5 Argmax and argmin return the indices of maximum and minimum values along an axis.

A = np.random.randint(10,size=(4,3))
A

array([[9, 6, 3],
       [9, 8, 7],
       [4, 7, 1],
       [8, 9, 1]])

In [74]:
# 6.  Random.random creates an array with random floats between 0 and 1. Same operation can be done with the random_sample function as well.

np.random.random(size=4)

array([0.44677392, 0.25034705, 0.2528519 , 0.7383943 ])

In [77]:
#7. Random.randint creates an array of integers in any shape.
array=([1,1,1,3,0,])
np.random.randint(10, size=(3,4))

array([[5, 8, 9, 0],
       [9, 2, 5, 6],
       [7, 2, 1, 8]])

In [82]:
#8. Random.randn returns a sample or samples from the standard normal distribution (i.e. Zero mean and unit variance).
a = np.random.randn(10000)
print(a.mean())
print(a.var())


-0.010029850403422396
1.0108478274184916


In [ ]:
pd.Series(a).plot('kde', figsize=(8,5))

In [83]:
# 9.  Random.shuffle modifies the sequence of an array by shuffling its elements.
a=np.array([0,1,2,3,4,5,6,7,8,9])
np.random.shuffle(a)
a

array([5, 3, 4, 6, 7, 0, 9, 8, 2, 1])

In [85]:
#10. Reshape it changes the shape of an array. The overall size must be maintained
A=np.random.randint(10, size=(3,4))
A

array([[3, 4, 1, 4],
       [4, 4, 8, 7],
       [3, 4, 5, 5]])

In [86]:
A.reshape(2,6)

array([[3, 4, 1, 4, 4, 4],
       [8, 7, 3, 4, 5, 5]])

In [87]:
A.reshape(-1,4)

array([[3, 4, 1, 4],
       [4, 4, 8, 7],
       [3, 4, 5, 5]])

In [88]:
# 11. Expand_dims It expands the dimension of an array.
a=np.array([1,2,3,4])
a.ndim

1

In [89]:
np.expand_dims(a,axis=0).ndim

2

In [92]:
#Count_nonzero returns the count of non-zero elements in an array which may come in handy when working with arrays with high sparsity
a=np.random.randint(0,5, size=100)
np.count_nonzero(a)

82

In [93]:
#Argwhere returns the indices of nonzero elements in an array.
A=np.random.randint(3,size=(2,3))
A

array([[0, 0, 1],
       [2, 2, 2]])

In [94]:
np.argwhere(A)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int64)

In [100]:
#14. Zeros, Ones, Full are three separate functions but what they do is very similar. They create arrays with zeros, ones, or a specific value.
np.zeros(3)


array([0., 0., 0.])

In [101]:

np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [102]:
np.full ((2,3), fill_value=4.2)

array([[4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2]])

In [103]:
#15Eye and Identity creates identity matrix with a specified dimension.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [104]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
# 16. Ravel returns a flattened array
A= np.random.randint(5, size=(2,3))
A


np.ravel(A)

array([1, 0, 2, 1, 3, 4])

In [109]:
# 17. Hsplit and Vsplit split arrays vertically (vsplit) or horizontally (hsplit).
A = np.random.randint(5, size=(4,4))
A



array([[3, 0, 3, 3],
       [0, 0, 3, 2],
       [1, 2, 0, 0],
       [2, 4, 1, 3]])

In [110]:
np.hsplit(A,2)[0]

array([[3, 0],
       [0, 0],
       [1, 2],
       [2, 4]])

In [111]:
np.hsplit(A, 2)[1]

array([[3, 3],
       [3, 2],
       [0, 0],
       [1, 3]])

In [112]:
np.vsplit(A,2)[0]

array([[3, 0, 3, 3],
       [0, 0, 3, 2]])

In [113]:
np.vsplit(A,2)[1]

array([[1, 2, 0, 0],
       [2, 4, 1, 3]])

In [114]:
#18. Hstack and Vstack stack arrays horizontally (column-wise) and vertically (rows on top of each other)
a=np.array([1,1,1,2])
b= np.array([2,3,4,5])


In [115]:
np.vstack((a,b))

array([[1, 1, 1, 2],
       [2, 3, 4, 5]])

In [ ]:



21. Round and Around
Both of them round up the floats to a specified number of decimal points.


We have covered only a part of the operations that we can do with NumPy. However, these are the operations that you are likely to use in a typical data analysis and manipulation process.

NumPy proved to be a very flexible and efficient scientific computing library. It serves as a base for many Python libraries such as Pandas.

Thank you for reading. Please let me know if you have any feedback.



In [116]:
# 19. Transpose nsposes an array. In case of 2-dimensional arrays (i.e. matrix), transposing means switching rows and columns.
A = np.random.randint(5, size=(3,4))

In [117]:
A.transpose()

array([[0, 2, 4],
       [2, 4, 0],
       [2, 0, 0],
       [0, 1, 1]])

In [120]:
# 20. Abs and Absolute return the absolute values of elements in an array.
A = np.random.randint(-5, 5, size=(2,3))
A

array([[ 2, -5,  3],
       [-5, -2,  3]])

In [122]:
np.abs(A)

array([[2, 5, 3],
       [5, 2, 3]])

In [123]:
# 21. Round and Around Both round up the floats to a specified number of decimal points.

a=np.random.random(5)
a

array([0.98823422, 0.03383282, 0.01961645, 0.08950119, 0.49867975])

In [124]:
np.round(a,2)

array([0.99, 0.03, 0.02, 0.09, 0.5 ])

In [125]:
np.round(a,3)

array([0.988, 0.034, 0.02 , 0.09 , 0.499])